namespace: capi-microk8s-control-plane-system

namePrefix: capi-microk8s-control-plane-

commonLabels:
  cluster.x-k8s.io/provider: "control-plane-microk8s"

resources:
  - ../../config/manager


patchesStrategicMerge:
  - ../../config/default/manager_auth_proxy_patch.yaml

patchesJson6902:
  - target:
      group: apps
      kind: Deployment
      name: controller-manager
      namespace: system
      version: v1
    path: patch_service_account.yaml
  - target:
      group: apps
      kind: Deployment
      name: controller-manager
      namespace: system
      version: v1
    path: patch_healthcheck.yaml