namespace: capi-webhook-system

namePrefix: capi-microk8s-control-plane-

commonLabels:
  cluster.x-k8s.io/provider: "control-plane-microk8s"

bases:
  - ../../config/crd
#  - ../../config/manager
#  - ../../../controlplane/kubeadm/config/webhook
#  - ../../../controlplane/kubeadm/config/certmanager

#patchesStrategicMerge:
#  - ../../config/crd/patches/webhook_in_microk8scontrolplanes.yaml
#  - ../../config/crd/patches/cainjection_in_microk8scontrolplanes.yaml

#vars:
#  - name: CERTIFICATE_NAMESPACE # namespace of the certificate CR
#    objref:
#      kind: Certificate
#      group: cert-manager.io
#      version: v1
#      name: serving-cert # this name should match the one in certificate.yaml
#    fieldref:
#      fieldpath: metadata.namespace
#  - name: CERTIFICATE_NAME
#    objref:
#      kind: Certificate
#      group: cert-manager.io
#      version: v1
#      name: serving-cert # this name should match the one in certificate.yaml
#  - name: SERVICE_NAMESPACE # namespace of the service
#    objref:
#      kind: Service
#      version: v1
#      name: webhook-service
#    fieldref:
#      fieldpath: metadata.namespace
#  - name: SERVICE_NAME
#    objref:
#      kind: Service
#      version: v1
#      name: webhook-service

configurations:
  - ../../config/crd/kustomizeconfig.yaml

#patchesJson6902:
#  - target:
#      group: apps
#      kind: Deployment
#      name: controller-manager
#      namespace: system
#      version: v1
#    path: patch_service_account.yaml
#  - target:
#      group: apiextensions.k8s.io
#      version: v1
#      kind: CustomResourceDefinition
#      name: kubeadmcontrolplanes.controlplane.cluster.x-k8s.io
#    path: patch_crd_webhook_namespace.yaml
